name: Pycroglia Core package integration tests

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"

      - name: Set up Python
        run: uv python install

      - name: Install core and core-test dependencies
        run: uv sync --group core --group core-test

      - name: Run core package integration tests
        run: |
          set -o pipefail
          uv run pytest ./pycroglia/core/tests/integration
